{
 "title": "Xerox AltaLink - Yazici Izleme",
 "tags": [
  "printer",
  "xerox"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "## Toner Kartuslari" } },
  {
   "title": "Siyah",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Black Toner %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Cam Gobegi",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Cyan Toner %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Kirmizi",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Magenta Toner %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Sari",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Yellow Toner %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "## Drum Kartus ve Servis Parcalari"
   }
  },
  {
   "title": "Drum R1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Drum Cartridge R1 %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Drum R2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Drum Cartridge R2 %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Drum R3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Drum Cartridge R3 %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Drum R4",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Drum Cartridge R4 %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Transfer Belt",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Transfer Belt Cleaner %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Bias Transfer",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": {
      "filter": "Xerox: Second Bias Transfer Roll %"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Atik Toner",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Waste Toner Container %" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "options": { "content": "## Kagit Tepsileri" } },
  {
   "title": "Tepsi 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "sheets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Tray 1 Paper Level" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Tepsi 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "sheets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Tray 2 Paper Level" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Tepsi 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "sheets" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Tray 3 Paper Level" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 }, "options": { "content": "## Baski Sayaclari" } },
  {
   "title": "Toplam",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Total Impressions" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Siyah",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Black Impressions" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Renkli",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Color Impressions" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Siyah Sayfa",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Black Printed Sheets" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 }, "options": { "content": "## Sistem" } },
  {
   "title": "Durum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Xerox: Printer Status" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Baglanti",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Gecikme",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Calisma Suresi",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "uptime" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Printers" },
     "host": {
      "filter": "Xerox AltaLink C8255 (192.168.43.225)"
     },
     "item": { "filter": "Uptime (network)" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}